### ISSUE TITLE
An error is cought

### ISSUE THREAD

**Issue by Lurito** [cxwithyxy/Neuroevolution_T-rex#2]
OS: Windows Server 2003 SP2

Explorer: 49.0.2623.112

Environment: Both online and on localhost

Log:
Uncaught SyntaxError: Unexpected token function  (neataptic.js:1470)
Uncaught ReferenceError: neataptic is not defined  (index.js:6)

**Comment by Lurito** [comment]
Explorer: Google Chrome 49.0.2623.112

**Comment by cxwithyxy** [comment]
neataptic.js 使用了 async 保留关键字。
Neataptic.js uses the “async” reserved keyword.

对于ECMAScript 5/6 来说，async 保留关键字是一个新特性。
For ECMAScript 5/6, the “async” reservation keyword is a new feature.

可能你的Chrome 49并不支持一些javascript的新特性（包括 async）。
Maybe Chrome 49 does not support some of the new features of JavaScript (including async).

你可以通过 http://kangax.github.io/compat-table/es2016plus/ 查询浏览器的兼容情况。
You can query the compatibility of the browser by http://kangax.github.io/compat-table/es2016plus/

我认为你更新Chrome到62版本之后，这些问题都能解决了。
I think these problems can be solved after you update Chrome to version 62.

**Comment by Lurito** [comment]
感谢您的详细回复。
很遗憾，Chrome 49 是支持 Windows XP / 2003 和 Vista 的最后一个版本，因此可能无法在更换系统前更新浏览器。不知是否有替代的解决方案来支持这些系统？

**Comment by cxwithyxy** [comment]
我在我的虚拟机上安装了windows xp系统，经过我的测试，360极速浏览器是支持这些javascript新特性的。
I installed the Windows XP system on my virtual machine, and after my test, 360极速 browsers are supporting these new features of JavaScript.

因此它已经成功把Neuroevolution_T-rex运行起来了。
So it has succeeded in running Neuroevolution_T-rex.

你可以从这里下载这个浏览器 http://chrome.360.cn/
You can download this browser from here http://chrome.360.cn/

**Comment by Lurito** [comment]
感谢！
